name: $NAME - Publish

on:
  push:
    branches:
      - main
    paths:
      - $NAME/Dockerfile
      - .github/workflows/$NAME.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Buildx
        uses: "./.github/actions/setup-buildx"
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_ip: ${{ secrets.SSH_IP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          name: $NAME
