ARG UBUNTU_VERSION=22.04

FROM ubuntu:$UBUNTU_VERSION as build
WORKDIR /

RUN apt-get update && \
    apt-get install -y build-essential git

RUN git clone --depth=1 https://github.com/ggerganov/llama.cpp.git
WORKDIR /llama.cpp

RUN make

FROM ubuntu:$UBUNTU_VERSION as runtime

COPY --from=build /llama.cpp/main /main

ENTRYPOINT [ "/main" ]