name: "Setup Buildx"
description: "Sets up buildx using my oracle VPS as a builder for arm images"

# to build the arm image, qemu is too slow
# so I use my personal Oracle VPS as a buildx builder via ssh for native arm builds

inputs:
  ssh_private_key:
    description: "The private key to use to connect to the builder"
    required: true
  ssh_user:
    description: "The user to use to connect to the builder"
    required: true
  ssh_ip:
    description: "The IP to use to connect to the builder"
    required: true
  GTIHUB_TOKEN:
    description: "The token to use to connect to the builder"
    required: true
  name:
    description: "The name of the image"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
        uses: actions/checkout@v3

    - name: Setup Buildx
      uses: "./.github/actions/setup-buildx"
      with:
        ssh_private_key: ${{ inputs.SSH_PRIVATE_KEY }}
        ssh_user: ${{ inputs.SSH_USER }}
        ssh_ip: ${{ inputs.SSH_IP }}

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.GITHUB_TOKEN }}

    # I don't need to keep track of previous versions, so I just use latest
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ${{ input.name }}
        platforms: linux/arm64,linux/amd64
        push: true
        tags: ghcr.io/${{ github.repository }}/${{ input.name }}:latest
        cache-from: type=gha,scope=${{ input.name }}
        cache-to: type=gha,mode=max,scope=${{ input.name }}
