name: docker-postgres-upgrade - Publish

on:
  push:
    branches:
      - main
    paths:
      - images/docker-postgres-upgrade/**
      - .github/workflows/docker-postgres-upgrade.yml
      - .github/actions/setup-buildx/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sub-image:
          - 15-to-17
          - 16-to-17
      max-parallel: 1 # build sequentially
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
  
      - name: Setup Buildx
        uses: "./.github/actions/setup-buildx"
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_ip: ${{ secrets.SSH_IP }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # I don't need to keep track of previous versions, so I just use latest
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: images/docker-postgres-upgrade/docker-postgres-upgrade/${{ matrix.sub-image }}
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}/docker-postgres-upgrade:${{ matrix.sub-image }}
          cache-from: type=gha,scope=docker-postgres-upgrade-${{ matrix.sub-image }}
          cache-to: type=gha,mode=max,scope=docker-postgres-upgrade-${{ matrix.sub-image }}
