name: Docker x11 Bridge - Publish

on:
  push:
    branches:
      - main
    paths:
      - docker-x11-bridge/*
      - .github/workflows/docker-x11-bridge.yml

permissions:
  packages: write
  contents: read

jobs:
  build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Setup Buildx
        uses: "./.github/actions/setup-buildx"
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_ip: ${{ secrets.SSH_IP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          name: docker-x11-bridge
