name: Julia Devcontainer - Publish

on:
  push:
    branches:
      - main
    paths:
      - containers/julia-devcontainer/Dockerfile
      - .github/workflows/julia-devcontainer.yml
  # rebuild every week
  # https://crontab.guru/every-week
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:


permissions:
  packages: write
  contents: read

jobs:
  build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push
        uses: "./.github/actions/build-and-push"
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_ip: ${{ secrets.SSH_IP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          name: julia-devcontainer
