name: llama-cpp - Publish

# this is quite a bit different from the other workflows, since we need a matrix build

on:
  push:
    branches:
      - main
    paths:
      - images/llama-cpp/Dockerfile
      - .github/workflows/llama-cpp.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { tag: "light", dockerfile: "Dockerfile.main" }
          - { tag: "full", dockerfile: "Dockerfile.full" }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: "./.github/actions/setup-buildx"
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_ip: ${{ secrets.SSH_IP }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image (tagged)
        uses: docker/build-push-action@v5
        with:
          file: containers/llama-cpp/${{ matrix.config.dockerfile }}
          context: containers/llama-cpp
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}/llama.cpp:${{ matrix.config.tag }}
