name: Deploy Purescript-Spago Image

on:
  push:
    branches:
      - main
    paths:
      - purescript-spago/Dockerfile
      - .github/workflows/purescript-spago.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Buildx
        uses: "./.github/actions/setup-buildx"
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_ip: ${{ secrets.SSH_IP }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: purescript-spago
          platforms: linux/arm64,linux/amd64
          file: purescript-spago/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/purescript-spago:latest
            ghcr.io/${{ github.repository }}/purescript-spago:$(date +'%Y-%m-%d')
          cache-from: type=gha,scope=purescript-spago
          cache-to: type=gha,mode=max,scope=purescript-spago